#!/bin/bash

echo "UPS initiated Shutdown Sequence" | ${WALL}

curl -s \
  --form-string "token=$PUSHOVERTOKEN" \
  --form-string "user=$PUSHOVERUSER" \
  --form-string "message=apcupsd is initiating cluster shutdown" \
  --form-string "priority=1" \
  https://api.pushover.net/1/messages.json > /dev/null 2>&1

VMS=$(ha-manager status | grep started | awk '{print $2}')

if [ -z "$VMS" ] 
then
  echo "No started HA VMs"   
else 
  printf "$VMS" | xargs -n 1 ha-manager set --state disabled 
  echo "Disabling the following VMs:\n $VMS"
fi 

for ip in $(pvecm status | grep -Po '((?:(?:25[0-5]|(?:2[0-4]|1\d|[1-9]|)\d)\.?\b){4})$'); do
  echo "Sending shutdown command to $ip"
  ssh root@$ip 'shutdown -h now'
done

${SHUTDOWN} -h now "apcupsd UPS initiated shutdown"
exit 0