#!/bin/bash

echo "UPS initiated Shutdown Sequence" | ${WALL}

curl -s \
  --form-string "token=$PUSHOVERTOKEN" \
  --form-string "user=$PUSHOVERUSER" \
  --form-string "message=PVE is initiating system shutdown" \
  --form-string "priority=1" \
  https://api.pushover.net/1/messages.json > /dev/null 2>&1

VMS=$(ha-manager status | grep started | awk '{print $2}')

if [ -z "$VMS" ] 
then
    echo "No started HA VMs"   
else 
    printf "$VMS" | xargs -n 1 ha-manager set --state disabled 
    echo "Disabling the following VMs:\n $VMS"
fi 

ssh root@10.0.0.51 'shutdown -h now'  #replace and/or replicate for correct nodes

${SHUTDOWN} -h now "apcupsd UPS initiated shutdown"
exit 0