#!/bin/sh
#
# This shell script if placed in /etc/apcupsd
# will be called by /etc/apcupsd/apccontrol when the UPS
# goes on batteries.
# We send an email message to root to notify him.
#

curl -s \
  --form-string "token=$PUSHOVERTOKEN" \
  --form-string "user=$PUSHOVERUSER" \
  --form-string "message=apcupsd: On battery - $(apcaccess | grep TIMELEFT)" \
  --form-string "priority=1" \
  https://api.pushover.net/1/messages.json > /dev/null 2>&1

exit 0
